import test from "node:test";
import assert from "node:assert/strict";
import { createStore } from "./store.mjs";
import { runContentJob, startContentWorker } from "./content-pipeline.mjs";

const catalog={source:"fixture",sourceSha256:"a".repeat(64),rulesVersion:"v1",coverage:"fixture",places:[{placeId:"osm:node:1",osmType:"node",osmId:1,name:"Памятник без адреса",location:{lat:55.75,lon:37.61},tags:{historic:"memorial",wikidata:"Q1"}}]};
function fixture(t,{audio=false}={}){const store=createStore(":memory:",{maxDaily:100,maxActive:100});t.after(()=>store.close());store.importPlaces(catalog);store.createBatch({requestKey:`pipeline-${audio?"audio":"text"}`,limit:1,mode:audio?"text-and-audio":"text-only",ttsProfile:audio?"silero-ru-v1":null});const url="https://one.example/place",page="Памятник установлен в Москве и создан известным архитектором. ".repeat(12);const facts=[1,2,3].map(index=>({claim:`Факт ${index}`,topic:"place_history",scope:"building",location:"Памятник",distanceMeters:null,evidence:[{sourceId:"s1",quote:"Памятник установлен в Москве и создан известным архитектором."}]}));const part="Памятник установлен в Москве и связан с историей города. Источник рассказывает о его создании и работе архитектора. ".repeat(3).trim(),text=`${part}\n\n${part}`;const queue=[{text:"Найден официальный источник",sources:[{url,title:"Источник"}]},{value:{addressConfirmed:true,placeName:"Памятник",resolvedAddress:"Памятник, Москва",facts}},{text},{value:{approved:true,issues:[],paragraphFacts:[{paragraph:1,factIds:["f1","f2"]},{paragraph:2,factIds:["f2","f3"]}]}}];const provider={writerModel:"writer",response:async()=>({usage:{total_tokens:1},...queue.shift()})};return{store,provider,url,page,queue};}

test("OSM place uses plain writer text and one source",async t=>{const f=fixture(t);const result=await runContentJob(f.store.claimContentJob(),{store:f.store,provider:f.provider,fetchPage:async url=>({url,contentType:"text/html",html:f.page})});assert.equal(result.story.title,"Памятник");assert.equal(result.story.facts.length,3);});

test("auto approval queues audio only for full stories",async t=>{const f=fixture(t,{audio:true});const result=await runContentJob(f.store.claimContentJob(),{store:f.store,provider:f.provider,autoApprove:true,fetchPage:async url=>({url,contentType:"text/html",html:f.page})});assert.equal(result.story.audioDisposition,"eligible");assert.ok(f.store.claimExternalAudio({workerId:"gpu",requestId:"audio-request-0001",profileIds:["silero-ru-v1"]}));});

test("source access failure is distinct from missing evidence",async t=>{const f=fixture(t);const result=await runContentJob(f.store.claimContentJob(),{store:f.store,provider:f.provider,fetchPage:async()=>{throw Object.assign(new Error(),{code:"SOURCE_BLOCKED"});}});assert.equal(result.error.code,"SOURCE_ACCESS_FAILED");assert.equal(result.state,"retry_wait");});

test("content worker honors concurrency",async t=>{const places=Array.from({length:2},(_,index)=>({...catalog.places[0],placeId:`osm:node:${index+1}`,osmId:index+1,name:`Место ${index+1}`}));const store=createStore(":memory:",{maxDaily:100,maxActive:100});t.after(()=>store.close());store.importPlaces({...catalog,places});store.createBatch({requestKey:"pipeline-concurrency",limit:2});let active=0,peak=0,release;const gate=new Promise(resolve=>{release=resolve;});const provider={writerModel:"writer",response:async()=>{active++;peak=Math.max(peak,active);await gate;active--;throw Object.assign(new Error(),{code:"INSUFFICIENT_EVIDENCE"});}};const worker=startContentWorker({store,provider,concurrency:2});await new Promise(resolve=>setTimeout(resolve,20));assert.equal(peak,2);release();await worker.stop();});
