"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { accountApi, AuthUser, getSession, signOut, signOutEverywhere } from "../auth/client";
import { savedStories } from "../generator/offline";
import type { GenerationJob } from "../generator/types";
import "../auth/auth.css";

type Walk={id:string;title:string;revision:number;updatedAt:string};
type RequestItem={jobId:string;operation:string;createdAt:string};
type Favorite={type:string;id:string;createdAt:string};

export function Account(){
  const[user,setUser]=useState<AuthUser|null>(null),[walks,setWalks]=useState<Walk[]>([]),[requests,setRequests]=useState<RequestItem[]>([]),[favorites,setFavorites]=useState<Favorite[]>([]),[offlineStories,setOfflineStories]=useState<GenerationJob[]>([]),[name,setName]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let active=true;const signedOut=()=>location.replace("/login?returnTo=/account");let channel:BroadcastChannel|undefined;try{channel=new BroadcastChannel("otgolosok:auth");channel.addEventListener("message",signedOut);}catch{/* Browser storage event remains available. */}addEventListener("storage",signedOut);void(async()=>{try{const current=await getSession();if(!current){signedOut();return;}const[data,requestData,favoriteData,savedData]=await Promise.all([accountApi("/api/me/walks"),accountApi("/api/me/requests"),accountApi("/api/me/favorites"),savedStories().catch(()=>[])]);if(active){setUser(current);setName(current.name);setWalks(data.walks);setRequests(requestData.requests);setFavorites(favoriteData.favorites);setOfflineStories(savedData);}}catch(e){if(active)setError(e instanceof Error?e.message:"Ошибка");}})();return()=>{active=false;channel?.close();removeEventListener("storage",signedOut);};},[]);
  async function save(e:FormEvent){e.preventDefault();try{const data=await accountApi("/api/me",{method:"PATCH",body:JSON.stringify({name})});setUser(data.user);}catch(e){setError(e instanceof Error?e.message:"Ошибка");}}
  async function importDraft(){try{const raw=localStorage.getItem("otgolosok:walk:v1");if(!raw)throw new Error("На этом устройстве нет локального черновика.");const draft=JSON.parse(raw);if(!confirm(`Перенести локальную прогулку «${draft.title||"Моя прогулка"}»? Локальная копия останется на устройстве.`))return;const key="otgolosok:account:pending-import",importId=localStorage.getItem(key)||crypto.randomUUID();localStorage.setItem(key,importId);const data=await accountApi("/api/me/import",{method:"POST",body:JSON.stringify({importId,walk:{title:draft.title||"Моя прогулка",snapshot:draft}})});localStorage.removeItem(key);setWalks(current=>[data.result.walk,...current.filter(w=>w.id!==data.result.walk.id)]);}catch(e){setError(e instanceof Error?e.message:"Ошибка импорта");}}
  async function logout(all=false){try{await(all?signOutEverywhere():signOut());}catch(e){setError(e instanceof Error?e.message:"Вы вышли локально.");}finally{localStorage.removeItem("otgolosok:account:last");location.replace("/");}}
  async function removeAccount(){if(!confirm("Удалить аккаунт, прогулки и избранное без возможности восстановления?"))return;try{await accountApi("/api/me/delete-code",{method:"POST",body:"{}"});const code=prompt("Код удаления отправлен на вашу почту. Введите шесть цифр:");if(!code)return;await accountApi("/api/me",{method:"DELETE",body:JSON.stringify({code})});location.replace("/");}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить аккаунт.");}}
  return <main className="account-shell"><header><Link href="/" className="wordmark">Отголосок<span>.</span></Link></header><section className="account-panel"><p className="kicker">Личный кабинет</p><h1>{user?.name??"Загрузка…"}</h1>{error&&<p role="alert" className="form-error">{error}</p>}{user&&<><p>{user.email}</p><form onSubmit={save}><label>Имя<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button className="account-button">Сохранить профиль</button></form><h2>Мои прогулки</h2>{walks.length?<ul className="account-list">{walks.map(w=><li className="account-item" key={w.id}><Link href={`/walk?id=${w.id}`}><strong>{w.title}</strong></Link><br/><small>{new Date(w.updatedAt).toLocaleString("ru")}</small></li>)}</ul>:<p>Пока нет сохранённых прогулок.</p>}<h2>Сохранено на устройстве</h2>{offlineStories.length?<ul className="account-list">{offlineStories.map(item=><li className="account-item" key={item.id}><Link href={`/create?job=${item.id}`}><strong>{item.story?.title||"Сохранённая история"}</strong></Link><br/><small>{item.address} · доступно без сети</small></li>)}</ul>:<p>Пока нет историй для прослушивания без сети.</p>}<p className="account-note">Откройте готовую историю и выберите «Сохранить для прогулки без сети». Четыре записи первой прогулки сохраняются автоматически.</p><h2>Запросы</h2>{requests.length?<ul className="account-list">{requests.map(item=><li className="account-item" key={`${item.jobId}:${item.createdAt}`}><Link href={`/create?job=${item.jobId}`}>{item.operation==="walk_research"?"Исследование прогулки":"История"}</Link><br/><small>{new Date(item.createdAt).toLocaleString("ru")}</small></li>)}</ul>:<p>Запросов пока нет.</p>}<h2>Избранное</h2>{favorites.length?<ul className="account-list">{favorites.map(item=><li className="account-item" key={`${item.type}:${item.id}`}>{item.type}: {item.id}</li>)}</ul>:<p>Избранного пока нет.</p>}<div className="account-actions"><Link href="/walk" className="account-button">Собрать прогулку</Link><button className="text-button" onClick={()=>void importDraft()}>Импортировать черновик с устройства</button><button className="text-button" onClick={()=>logout()}>Выйти</button><button className="text-button" onClick={()=>logout(true)}>Выйти везде</button><button className="text-button" onClick={()=>void removeAccount()}>Удалить аккаунт</button></div></>}</section></main>;
}
