#!/usr/bin/env python3
"""Build the offline Moscow stop catalog from the same OSM PBF as Valhalla.

Requires osmium==4.3.1 in a build-only Python environment; see content/walk-builder.md.
"""

import argparse
import hashlib
import json
from pathlib import Path

import osmium


def building_tags(tags):
    keys = ("name", "building", "addr:street", "addr:housenumber", "historic", "heritage", "tourism")
    selected = {key: tags[key] for key in keys if key in tags}
    if not all(selected.get(key) for key in keys[:4]) or selected["building"] == "no":
        return None
    if not (selected.get("historic", "no") != "no" or selected.get("heritage", "no") != "no" or selected.get("tourism") == "museum"):
        return None
    return selected


class Buildings(osmium.SimpleHandler):
    def __init__(self):
        super().__init__()
        self.elements = []
        self.latest_timestamp = ""
        self.skipped_geometry = 0

    def add(self, kind, osm_id, tags, points, timestamp):
        if not points:
            self.skipped_geometry += 1
            return
        lat = round((min(p[0] for p in points) + max(p[0] for p in points)) / 2, 7)
        lon = round((min(p[1] for p in points) + max(p[1] for p in points)) / 2, 7)
        if 55.48 <= lat <= 55.98 and 37.30 <= lon <= 37.95:
            self.elements.append({"type": kind, "id": osm_id, "center": {"lat": lat, "lon": lon}, "tags": tags})
            self.latest_timestamp = max(self.latest_timestamp, timestamp.isoformat())

    def node(self, node):
        tags = building_tags(node.tags)
        if tags:
            self.add("node", node.id, tags, [(node.lat, node.lon)], node.timestamp)

    def way(self, way):
        tags = building_tags(way.tags)
        if tags:
            points = [(n.lat, n.lon) for n in way.nodes] if all(n.location.valid() for n in way.nodes) else []
            self.add("way", way.id, tags, points, way.timestamp)

    def area(self, area):
        if area.from_way():
            return
        tags = building_tags(area.tags)
        if tags:
            points = [(n.lat, n.lon) for ring in area.outer_rings() for n in ring]
            self.add("relation", area.orig_id(), tags, points, area.timestamp)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pbf", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "backend/walk-discovery-catalog.mjs")
    args = parser.parse_args()
    handler = Buildings()
    handler.apply_file(str(args.pbf), locations=True, idx="flex_mem")
    if not handler.elements:
        raise SystemExit("No eligible Moscow buildings; refusing to replace the catalog")
    with args.pbf.open("rb") as source:
        checksum = hashlib.file_digest(source, "sha256").hexdigest()
    catalog = {
        "source": "https://download.bbbike.org/osm/bbbike/Moscow/Moscow.osm.pbf",
        "sourceSha256": checksum,
        "latestBuildingEdit": handler.latest_timestamp,
        "license": "ODbL-1.0",
        "attribution": "© OpenStreetMap contributors",
        "elements": sorted(handler.elements, key=lambda e: (e["type"], e["id"])),
    }
    # One record per line keeps the generated catalog compact and reviewable.
    records = ",\n".join(json.dumps(e, ensure_ascii=False, separators=(",", ":")) for e in catalog.pop("elements"))
    metadata = json.dumps(catalog, ensure_ascii=False, indent=2)
    args.output.write_text("// Generated by scripts/build-walk-discovery.py; do not edit by hand.\nconst catalog = " + metadata[:-2] + ',\n  "elements": [\n' + records + "\n  ]\n};\nexport default catalog;\n", encoding="utf-8")
    print(f"Wrote {len(handler.elements)} buildings; skipped {handler.skipped_geometry} incomplete geometries: {args.output}")


if __name__ == "__main__":
    main()
