#!/usr/bin/env python3
"""Build the offline Moscow stop catalog from the same OSM PBF as Valhalla.

Requires osmium==4.3.1 in a build-only Python environment; see content/walk-builder.md.
"""

import argparse
import hashlib
import json
import re
from pathlib import Path

import osmium

KEYS = ("name", "building", "addr:street", "addr:housenumber", "historic",
        "heritage", "tourism", "wikidata", "wikipedia", "architect")
REQUIRED = ("building", "addr:street", "addr:housenumber")
QID = re.compile(r"^Q[1-9][0-9]{0,15}$")


def notable(tags):
    """Signals that a building may carry researchable history.

    A name alone qualifies every shop and office tower, and many Moscow landmarks
    carry their title in the linked Wikidata item rather than in an OSM name tag.
    """
    return (tags.get("historic", "no") != "no"
            or tags.get("heritage", "no") != "no"
            or tags.get("tourism") == "museum"
            or bool(QID.match(tags.get("wikidata", "")))
            or bool(tags.get("wikipedia"))
            or bool(tags.get("architect")))


def building_tags(tags):
    selected = {key: tags[key] for key in KEYS if tags.get(key)}
    if not all(key in selected for key in REQUIRED) or selected["building"] == "no":
        return None
    return selected if notable(selected) else None


class Buildings(osmium.SimpleHandler):
    def __init__(self):
        super().__init__()
        self.elements = []
        self.latest_timestamp = ""
        self.skipped_geometry = 0
        self.unaddressed = 0

    def count_unaddressed(self, tags):
        # An address is the only handle the story pipeline has on a building, and
        # OSM rarely carries one nearby when the outline itself lacks it.
        if tags.get("building") and tags["building"] != "no" and notable(tags) and not all(key in tags for key in REQUIRED):
            self.unaddressed += 1

    def add(self, kind, osm_id, tags, points, timestamp):
        if not points:
            self.skipped_geometry += 1
            return
        lat = round((min(p[0] for p in points) + max(p[0] for p in points)) / 2, 7)
        lon = round((min(p[1] for p in points) + max(p[1] for p in points)) / 2, 7)
        if 55.48 <= lat <= 55.98 and 37.30 <= lon <= 37.95:
            self.elements.append({"type": kind, "id": osm_id, "center": {"lat": lat, "lon": lon}, "tags": tags})
            self.latest_timestamp = max(self.latest_timestamp, timestamp.isoformat())

    def node(self, node):
        tags = building_tags(node.tags)
        if tags:
            self.add("node", node.id, tags, [(node.lat, node.lon)], node.timestamp)
        else:
            self.count_unaddressed(node.tags)

    def way(self, way):
        tags = building_tags(way.tags)
        if tags:
            points = [(n.lat, n.lon) for n in way.nodes] if all(n.location.valid() for n in way.nodes) else []
            self.add("way", way.id, tags, points, way.timestamp)
        else:
            self.count_unaddressed(way.tags)

    def area(self, area):
        if area.from_way():
            return
        tags = building_tags(area.tags)
        if tags:
            points = [(n.lat, n.lon) for ring in area.outer_rings() for n in ring]
            self.add("relation", area.orig_id(), tags, points, area.timestamp)
        else:
            self.count_unaddressed(area.tags)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pbf", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "backend/walk-discovery-catalog.mjs")
    args = parser.parse_args()
    handler = Buildings()
    handler.apply_file(str(args.pbf), locations=True, idx="flex_mem")
    if not handler.elements:
        raise SystemExit("No eligible Moscow buildings; refusing to replace the catalog")
    with args.pbf.open("rb") as source:
        checksum = hashlib.file_digest(source, "sha256").hexdigest()
    catalog = {
        "source": "https://download.bbbike.org/osm/bbbike/Moscow/Moscow.osm.pbf",
        "sourceSha256": checksum,
        "latestBuildingEdit": handler.latest_timestamp,
        "license": "ODbL-1.0",
        "attribution": "© OpenStreetMap contributors",
        "elements": sorted(handler.elements, key=lambda e: (e["type"], e["id"])),
    }
    # One record per line keeps the generated catalog compact and reviewable.
    records = ",\n".join(json.dumps(e, ensure_ascii=False, separators=(",", ":")) for e in catalog.pop("elements"))
    metadata = json.dumps(catalog, ensure_ascii=False, indent=2)
    args.output.write_text("// Generated by scripts/build-walk-discovery.py; do not edit by hand.\nconst catalog = " + metadata[:-2] + ',\n  "elements": [\n' + records + "\n  ]\n};\nexport default catalog;\n", encoding="utf-8")
    print(f"Wrote {len(handler.elements)} buildings; skipped {handler.unaddressed} notable buildings without an address "
          f"and {handler.skipped_geometry} incomplete geometries: {args.output}")


if __name__ == "__main__":
    main()
